<?php
/*
 * messages.php
 * templates for the messages generated by the racebox application
 */



$m_entry_add_class = <<<EOT
The OOD created a new class [%s] during the event - record id %s.\n\nPlease check that the class has been configured correctly, and that it is allocated to the correct fleet in all the club formats.\n\nIn particular remember to check that its PN is correct according to the club's policies.\n
EOT;

$m_entry_add_competitor = <<<EOT
The OOD created a new competitor during the event - record id %s.\n\nClass: %s   Sail No.: %s   Helm: %s\n\nThe OOD only enters some limited information and there may be additional fields that your club uses - e.g. allocating them to a group \n\nPlease check that additional competitor information your club uses has been added.\n
EOT;


?>